---
- name: Inlcude zsh variables for specific OS
  include_vars: "{{ lookup('first_found', zsh_os_variable_files) }}"
  tags:
    - zsh
    - zinit

- name: Install zsh
  import_tasks: "install_zsh.yml"
  tags:
    - zsh
    - zinit
