---
- name: Converge
  remote_user: ansible
  hosts: all
  tasks:
    - name: "Include role zinit"
      import_role:
        name: nekeal.zinit
  vars:
    users:
      - username: ansible
        groups:
          - sudo
        shell: /bin/zsh
        aliases:
          aliases:
            l: ls -lart
